### ISSUE TITLE
Timestamp updates when application response message is updated

### ISSUE THREAD

**Issue by Selida95** [mattboy9921/MauveList#2]
When an application has been accepted or rejected, the timestamp for when the application was submitted gets updated to the current time.

**Comment by mattboy9921** [comment]
Hm, that is due to the way it rebuilds the message (essentially runs through the build again). To fix that, I'd have to see if there's a convenient way to store the original timestamp somewhere, perhaps in the application manager class. Or I could also see if there's a way to only modify the buttons on the message instead of the entire message. Not sure if that is possible.

**Comment by Selida95** [comment]
Timestamp still seems to be broken. Not sure if it can be fixed but I've added these images for the sake of recording it.

![image](https://user-images.githubusercontent.com/8844849/148891953-46c15b21-ad36-40e6-af0b-2f92a8d431fb.jpeg)
![image](https://user-images.githubusercontent.com/8844849/148891979-94e9e928-3da9-4fad-9a91-a417410f9dce.jpeg)
