### ISSUE TITLE
Optional Application Rejection Reason

### ISSUE THREAD

**Issue by Selida95** [mattboy9921/MauveList#3]
It would be nice to be able to give an optional reason for rejecting an application that appears in application status in the application channel and gets sent to the user by the application bot. For example, we could tell them that we need more information for a question.

**Comment by mattboy9921** [comment]
I suppose for a rejection, clicking the button could result in a message saying something like "Reason for rejecting application?" with a button saying "No reason" otherwise you'd type your response in the chat? Should it take the next message in the chat channel or only one from the person who hit the reject button? 

The other question is that if we choose to deny an application, should a message be sent if we don't want a reason? Or should it continue to be a silent rejection?

**Comment by Selida95** [comment]
Yeah. I think it should just take the next message from the person who hit the reject button. Although I doubt it would be a huge issue as there's only a few of us who have access to that channel and would be typing random things in it.

I think if the "No Reason" button is pressed, it should just be a silent rejection. But maybe this is something that could be configurable?

**Comment by mattboy9921** [comment]
Yeah, eventually more configuration options would be nice. For now I'll implement it like that.
