### ISSUE TITLE
Check username for invalid characters

### ISSUE THREAD

**Issue by mattboy9921** [mattboy9921/MauveList#8]
The first question for the application currently accepts any input. Some users will put "My username is blah" which screws up adding them.

It should at least check the username for invalid characters like punctuation or spaces and ask the user again for *just* their username. 
It may be possible to check whether the account is a valid account via Mojang's API but that would also require code to handle if Mojang's API goes down. Would we just fall back to checking invalid characters?

**Comment by Selida95** [comment]
We can use the Mojang API to validate the username ([https://wiki.vg/Mojang_API#Username_to_UUID](https://wiki.vg/Mojang_API#Username_to_UUID)) it's just a simple GET request. It returns the username and the UUID if it's valid, otherwise, it returns a 204 No Content error. 

If we're checking for invalid characters I think that should be enough if Mojang's API goes down. As you said, the request to Mojang's API would act as a double check that the username they have provided is correct.
